version: "3.8"
services:
  # create sql database with volumes
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
     # deployment configration resources
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2GB
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword12#
    volumes:
      - sqldata:/var/opt/mssql
    
  # create web app
  webapp:
    container_name: webapp
    image: stasi14bazarscr.azurecr.io/bazar
    build:
      dockerfile: ./SoftUniBazar/Dockerfile
    domainname: stasi14bazar
    ports:
      - "80:80"
    restart: on-failure

volumes:
  sqldata:
    # additinal volume driver options
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: stasi14bazarsa